#!/bin/bash

# Script de prueba para el sistema de chat con colas de mensajes
# Este script demuestra el funcionamiento del sistema

echo "🧪 Script de Prueba - Sistema de Chat con Colas de Mensajes"
echo "=========================================================="
echo ""

echo "📋 Instrucciones para probar el sistema:"
echo ""
echo "1. 🖥️  Terminal 1 - Ejecutar el servidor:"
echo "   ./servidor"
echo ""
echo "2. 👤 Terminal 2 - Cliente María:"
echo "   ./cliente María"
echo "   join General"
echo "   Hola a todos en General!"
echo "   /users"
echo ""
echo "3. 👤 Terminal 3 - Cliente Juan:"
echo "   ./cliente Juan"
echo "   join General"
echo "   Hola María!"
echo "   /list"
echo ""
echo "4. 👤 Terminal 4 - Cliente Camila:"
echo "   ./cliente Camila"
echo "   join Deportes"
echo "   ¿Alguien vio el partido del América?"
echo "   /leave"
echo ""
echo "🔧 Comandos útiles:"
echo "   ipcs -q                    # Ver colas de mensajes activas"
echo "   make clean-queues          # Limpiar colas"
echo ""
echo "✅ El sistema debe funcionar según el ejemplo del profesor"
